services:
    app:
        image: arm64v8/php:8.2-fpm
        container_name: tictactoe_app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - 8000:80
        networks:
            - tictactoe_network

    webserver:
        image: arm64v8/nginx:alpine
        container_name: tictactoe_webserver
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        ports:
            - 8080:80
        depends_on:
            - app
        networks:
            - tictactoe_network

    db:
        image: mysql:8.0
        container_name: tictactoe_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tictactoe
            MYSQL_USER: tictactoe
            MYSQL_PASSWORD: tictactoe
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - tictactoe_network

networks:
    tictactoe_network:
        driver: bridge

volumes:
    dbdata:
